### ISSUE TITLE
fix: Replace emoji for windows

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/fs-neo-org#39]
[Magic Wand](https://emojigraph.org/magic-wand/) (🪄) not available for windows:

<img width="485" alt="image" src="https://github.com/nspcc-dev/fs-neo-org/assets/32885629/db234a84-7426-4eb4-a400-f148acbb48b2">

**Comment by roman-khimov** [comment]
That explains a lot of things about Windows.

**Comment by roman-khimov** [comment]
We can now drop both of these emojies. It's no longer that how, it's just something that we use every day.

**Comment by mike-petrov** [comment]
with the emoji it stands out and makes you want to look there and click. For new people it should be good, what if you leave just the rocket?

**Comment by roman-khimov** [comment]
The plan for to remove them eventually to not distract from the main contents.
